name: llvm_clang_yml
resources:
- repo: self

queue:
  name: Hosted VS2017
  demands: cmake

steps:
  - checkout: self 
    submodules: true
  - script: build.bat
    displayName: 'cmake_script'
