name: llvm_clang_yml
resources:
- repo: self

checkout: self 
  submodules: true

queue:
  name: Hosted VS2017
  demands: cmake

steps:
  - script: build.bat
    displayName: 'cmake_script'
