name: llvm_clang_yml

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

resources:
- repo: self

variables:
  BuidDir: 'build'
  InstallDir: 'install'

jobs:
- job: string
  pool:
    vmImage: 'VS2017-Win2016'

  timeoutInMinutes: 240

  steps:
    - script: | 
        dir "D:/a/1/s/"
      displayName: Free space

    - checkout: self
      submodules: true
      
    - script: | 
        dir "D:/a/1/s/"
      displayName: Free space

    - script: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        CMake -G "Ninja" -H.\llvm -B.\$(BuidDir) -Thost=x64 -DCMAKE_INSTALL_PREFIX=$(InstallDir) -DLLVM_EXTERNAL_PROJECTS="clang" -DLLVM_EXTERNAL_CLANG_SOURCE_DIR=.\clang -DCMAKE_BUILD_TYPE=release -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_ENABLE_WARNINGS=OFF -DLLVM_ENABLE_CXX1Z=ON -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_DOCS=OFF
      displayName: CMake generation

    - script: | 
        dir "D:/a/1/s/"
      displayName: Free space

    - script: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        CMake --build .\$(BuidDir)
      displayName: CMake build-install
      timeoutInMinutes: 240
