name: llvm_clang_yml
resources:
- repo: self

checkout: self 
  submodules: true

pool:
  vmImage: 'VS2017-Win2016'
  demands: cmake

steps:
  - checkout: self
    submodules: true
    
  - script: build.bat
    displayName: 'cmake_script'
